apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghost-helm.fullname" . }}-secrets
  labels:
    {{- include "ghost-helm.labels" . | nindent 4 }}
type: Opaque
data:
  # Database credentials (base64 encoded)
  mysql-root-password: {{ .Values.secrets.database.rootPassword | b64enc | quote }}
  mysql-password: {{ .Values.secrets.database.password | b64enc | quote }}

  # Mail credentials (base64 encoded)
  mail-auth-user: {{ .Values.secrets.mail.auth.user | b64enc | quote }}
  mail-auth-password: {{ .Values.secrets.mail.auth.password | b64enc | quote }}
